// Catálogo D&D 5e PHB — PT-BR

export type DndSpellData = {
  name: string; level: number; school: string;
  castingTime: string; range: string; duration: string;
  componentV: boolean; componentS: boolean; componentM: boolean;
  materialComponent?: string; description: string; classes: string[];
};

function s(name:string,level:number,school:string,ct:string,range:string,dur:string,v:boolean,sc:boolean,m:boolean,mat:string,desc:string,classes:string[]):DndSpellData{
  return{name,level,school,castingTime:ct,range,duration:dur,componentV:v,componentS:sc,componentM:m,...(mat?{materialComponent:mat}:{}),description:desc,classes};
}

// ─── Truques (0) ──────────────────────────────────────────────────────────────
const CANTRIPS:DndSpellData[]=[
  s('Respingo Ácido',0,'Conjuração','1 ação','18 metros','Instantâneo',true,true,false,'','Um bolha de ácido atinge uma ou duas criaturas adjacentes (TR Destreza) causando 1d6 de dano ácido.',['Feiticeiro','Mago']),
  s('Proteção de Lâmina',0,'Abjuração','1 ação','Pessoal','1 turno',true,true,false,'','Você ganha resistência a dano cortante, perfurante e contundente até o início do seu próximo turno.',['Bardo','Bruxo','Feiticeiro','Mago']),
  s('Toque Gelado',0,'Necromancia','1 ação','18 metros','1 turno',true,false,false,'','Ataque mágico: 1d8 dano necrótico. O alvo não pode recuperar PV até o início do seu próximo turno. Vantagem contra mortos-vivos.',['Bruxo','Feiticeiro','Mago']),
  s('Luz Dançante',0,'Evocação','1 ação','36 metros','Concentração, 1 min',true,true,true,'Um pouco de fósforo ou vaga-lume','Cria até 4 luzes flutuantes ou uma figura humanoide de luz. Cada luz emite luz fraca em 3m.',['Bardo','Feiticeiro','Mago']),
  s('Druidismo',0,'Transmutação','1 ação','9 metros','1 turno',true,false,false,'','Sussurra mensagem de 25 palavras a planta ou besta natural. Cria efeitos naturais menores temporários.',['Druida']),
  s('Explosão Eldritch',0,'Evocação','1 ação','36 metros','Instantâneo',true,false,false,'','Raio de energia sinistra: ataque mágico, 1d10 dano de força. Mais raios em níveis maiores.',['Bruxo']),
  s('Projétil Ígneo',0,'Evocação','1 ação','36 metros','Instantâneo',false,true,false,'','Ataque mágico: 1d10 dano de fogo contra criatura ou objeto.',['Feiticeiro','Mago']),
  s('Amizade',0,'Encantamento','1 ação','Pessoal','Concentração, 1 min',false,true,true,'Um pouco de maquiagem','Vantagem em testes de Persuasão contra uma criatura não-hostil. Ao terminar, ela percebe que foi enfeitiçada.',['Bardo','Bruxo','Feiticeiro','Mago']),
  s('Orientação',0,'Adivinhação','1 ação','Toque','Concentração, 1 min',true,false,false,'','O alvo pode rolar 1d4 e adicionar em um teste de habilidade antes da magia terminar.',['Clérico','Druida']),
  s('Luz',0,'Evocação','1 ação','Toque','1 hora',true,false,true,'Um vaga-lume ou fósforo','Objeto toca emite luz intensa em 6m e fraca em mais 6m. TR Destreza para criaturas que carreguem o objeto.',['Bardo','Clérico','Feiticeiro','Mago']),
  s('Mão Mágica',0,'Conjuração','1 ação','9 metros','1 minuto',true,false,false,'','Mão espectral manipula objetos, abre portas, guarda/recupera itens. Carga máxima 5 kg.',['Bardo','Bruxo','Feiticeiro','Mago']),
  s('Remendar',0,'Transmutação','1 minuto','Toque','Instantâneo',true,false,true,'Dois pedaços de ferro magnetizado','Repara uma fratura ou rasgão de até 30 cm em objeto ou criatura. Não pode reparar o Golem de Ferro ou similares.',['Bardo','Clérico','Druida','Mago']),
  s('Mensagem',0,'Transmutação','1 ação','36 metros','1 turno',false,true,true,'Um pouco de fio de cobre','Sussurra mensagem para criatura. Ela pode responder em sussurro que só você ouve.',['Bardo','Feiticeiro','Mago']),
  s('Ilusão Menor',0,'Ilusão','1 ação','9 metros','1 minuto',false,true,true,'Um pouco de lã de carneiro','Cria um som ou imagem inanimada (até cubo de 1,5m). Sem cheiro, tato ou temperatura.',['Bardo','Bruxo','Mago']),
  s('Sopro Venenoso',0,'Conjuração','1 ação','1,5 metro','Instantâneo',false,true,false,'','Nuvem de gás: TR Constituição ou 1d12 dano de veneno.',['Druida','Feiticeiro','Mago','Bruxo']),
  s('Prestidigitação',0,'Transmutação','1 ação','3 metros','1 hora',true,false,false,'','Truques mágicos menores: acender chamas, limpar objetos, aquecer/esfriar material, criar efeitos sensoriais temporários.',['Bardo','Bruxo','Feiticeiro','Mago']),
  s('Produzir Chama',0,'Conjuração','1 ação','Pessoal','10 minutos',true,false,false,'','Chama na mão ilumina 3m. Pode arremessar: ataque mágico, 1d8 dano de fogo.',['Druida']),
  s('Raio de Gelo',0,'Evocação','1 ação','18 metros','Instantâneo',false,true,false,'','Ataque mágico: 1d8 dano frio e velocidade do alvo reduz em 3m até o início do próximo turno.',['Feiticeiro','Mago']),
  s('Resistência',0,'Abjuração','1 ação','Toque','Concentração, 1 min',true,false,true,'Um pano de couro','O alvo rola 1d4 e adiciona em um TR à sua escolha antes da magia terminar.',['Clérico','Druida']),
  s('Chama Sagrada',0,'Evocação','1 ação','18 metros','Instantâneo',true,false,false,'','TR Destreza ou 1d8 dano radiante. O alvo não se beneficia de cobertura neste TR.',['Clérico']),
  s('Cacete Mágico',0,'Transmutação','1 ação bônus','Toque','Concentração, 1 min',true,false,true,'Visco, folha de trevo','Transforma sua maça ou cajado: use Sab para ataque/dano e causa 1d8 dano contundente.',['Druida']),
  s('Choque',0,'Evocação','1 ação','Toque','Instantâneo',true,true,false,'','Ataque corpo a corpo: 1d8 dano elétrico. Se o alvo usa armadura metálica, tem desvantagem no próximo ataque.',['Feiticeiro','Mago']),
  s('Poupar o Moribundo',0,'Necromancia','1 ação','Toque','Instantâneo',true,false,false,'','Estabiliza uma criatura com 0 PV. Não funciona em mortos-vivos e constructos.',['Clérico']),
  s('Taumaturgia',0,'Transmutação','1 ação','9 metros','1 minuto',true,false,false,'','Manifesta sinal menor de poder sobrenatural: voz trovejante, chão tremendo, portas escancarando.',['Clérico']),
  s('Chicote de Espinhos',0,'Transmutação','1 ação','9 metros','Instantâneo',true,false,false,'','Ataque mágico: 1d6 dano perfurante. Se Grande ou menor, puxe o alvo 3m em sua direção.',['Druida']),
  s('Golpe Certeiro',0,'Adivinhação','1 ação','18 metros','Concentração, 1 turno',false,true,false,'','Você obtém vantagem no próximo ataque contra o alvo antes do fim do seu próximo turno.',['Bardo','Bruxo','Feiticeiro','Mago']),
  s('Zombaria Viciosa',0,'Encantamento','1 ação','18 metros','Instantâneo',true,false,false,'','TR Sabedoria ou 1d4 dano psíquico e desvantagem no próximo ataque até o fim do próximo turno.',['Bardo']),
  s('Dobrar o Sino',0,'Necromancia','1 ação','18 metros','Instantâneo',true,false,false,'','TR Sab ou 1d8 necrótico (doente: 1d12). Não funciona em mortos-vivos.',['Clérico','Mago','Bruxo']),
  s('Palavra de Radiância',0,'Evocação','1 ação','1,5 metro','Instantâneo',true,false,false,'','Cada criatura hostil em 1,5m deve TR Constituição ou sofrer 1d6 dano radiante.',['Clérico']),
  s('Estalo Trovejante',0,'Evocação','1 ação','Pessoal (5 metros)','Instantâneo',false,true,false,'','Cada criatura dentro de 1,5m deve TR Constituição ou sofrer 1d6 trovejante. O estalo é audível por 90m.',['Bardo','Druida','Feiticeiro','Mago','Patrulheiro','Bruxo']),
  s('Lâmina de Chama Verde',0,'Evocação','1 ação','Pessoal (raio de 1,5m)','Instantâneo',false,true,false,'','Ataque de arma: no acerto, fogo salta para criatura adjacente e causa 1d8 fogo. Escala em níveis maiores.',['Bruxo','Feiticeiro','Mago']),
];

// ─── Nível 1 ──────────────────────────────────────────────────────────────────
const LEVEL_1:DndSpellData[]=[
  s('Alarme',1,'Abjuração','1 minuto (ritual)','9 metros','8 horas',true,false,true,'Um pequeno sino e um pedaço de fio de prata','Cria um alarme (mental ou sonoro) para uma área de até 4,5m de cubo. Dispara quando criatura Minúscula+ entra.',['Mago','Patrulheiro']),
  s('Amizade Animal',1,'Encantamento','1 ação','9 metros','24 horas',true,false,true,'Comida','Uma besta com Int 3 ou menos deve TR Sab ou fica enfeitiçada por você (amigável).',['Bardo','Druida','Patrulheiro']),
  s('Armadura de Agathys',1,'Abjuração','1 ação','Pessoal','1 hora',true,false,true,'Uma xícara de água','Ganha 5 PV temporários. Enquanto durarem, criaturas que te acertarem em corpo a corpo sofrem 5 dano frio.',['Bruxo']),
  s('Absorver Elementos',1,'Abjuração','1 reação','Pessoal','1 turno',false,true,false,'','Reação ao sofrer dano de ácido/frio/fogo/elétrico/trovejante: resistência ao dano e o primeiro ataque corpo a corpo no próximo turno causa 1d6 extra desse tipo.',['Druida','Mago','Patrulheiro']),
  s('Impor',1,'Encantamento','1 ação','9 metros','Concentração, 1 min',true,false,true,'Uma gota de sangue','Até três criaturas devem TR Carisma ou subtraem 1d4 de jogadas de ataque e TRs por 1 minuto.',['Bardo','Clérico']),
  s('Mãos Flamejantes',1,'Evocação','1 ação','Pessoal (cone de 4,5m)','Instantâneo',true,true,false,'','TR Destreza ou 3d6 dano de fogo (metade em sucesso) em cone de 4,5m.',['Feiticeiro','Mago']),
  s('Causar Medo',1,'Necromancia','1 ação','18 metros','Concentração, 1 min',true,false,false,'','TR Sab ou fica amedrontado de você. TR repetido no fim de cada turno.',['Bruxo']),
  s('Enfeitiçar Pessoa',1,'Encantamento','1 ação','9 metros','Concentração, 1h',true,false,false,'','Humanoide TR Sab ou fica enfeitiçado. É amigável; vantagem em interações sociais.',['Bardo','Clérico','Druida','Feiticeiro','Mago','Bruxo']),
  s('Raio Cromático',1,'Evocação','1 ação','27 metros','Instantâneo',true,true,true,'Um diamante de 50 po','Ataque mágico com raio de cor aleatória (1d8): fogo, frio, elétrico, ácido, veneno, frio, radiante ou múltiplo.',['Feiticeiro','Mago']),
  s('Aspersão de Cores',1,'Ilusão','1 ação','Pessoal (cone de 4,5m)','1 turno',true,true,true,'Uma pitada de pó de pimenta e areia',  'Criaturas com até 6d10 PV no cone ficam cegas até o fim do seu próximo turno.',['Feiticeiro','Mago']),
  s('Comando',1,'Encantamento','1 ação','18 metros','1 turno',true,false,false,'','Humanoide TR Sab ou segue um comando de uma palavra (fugir, prostrar, parar, largar, aproximar).',['Clérico','Paladino']),
  s('Duelo Compelido',1,'Encantamento','1 ação bônus','9 metros','Concentração, 1 min',true,false,false,'','Criatura TR Carisma ou fica compelida a lutar com você e tem desvantagem em ataques contra outros.',['Paladino']),
  s('Compreender Idiomas',1,'Adivinhação','1 ação (ritual)','Pessoal','1 hora',true,false,true,'Uma pitada de fuligem e sal','Entende qualquer idioma falado ou escrito por 1 hora.',['Bardo','Feiticeiro','Mago','Bruxo']),
  s('Criar ou Destruir Água',1,'Transmutação','1 ação','9 metros','Instantâneo',true,false,true,'Uma gota de água ou alguns grãos de areia','Cria ou destrói até 40 litros de água.',['Clérico','Druida']),
  s('Cura Ferimentos',1,'Evocação','1 ação','Toque','Instantâneo',true,false,false,'','Recupera 1d8 + mod conjuração em PV. Não funciona em mortos-vivos e constructos.',['Bardo','Clérico','Druida','Paladino','Patrulheiro']),
  s('Detectar Magia',1,'Adivinhação','1 ação (ritual)','Pessoal','Concentração, 10 min',true,false,false,'','Percebe magia em 9m. Como ação, vê aura em criaturas/objetos que carregam magia e identifica a escola.',['Bardo','Clérico','Druida','Paladino','Patrulheiro','Feiticeiro','Mago']),
  s('Detectar Veneno e Doença',1,'Adivinhação','1 ação (ritual)','Pessoal','Concentração, 10 min',true,false,true,'Uma folha de iosum','Percebe venenos, animais venenosos e doenças em 9m.',['Clérico','Druida','Paladino','Patrulheiro']),
  s('Favor Divino',1,'Evocação','1 ação bônus','Pessoal','Concentração, 1 min',true,false,false,'','Ataques de arma causam 1d4 extra de dano radiante enquanto concentrado.',['Paladino']),
  s('Disfarce',1,'Ilusão','1 ação','Pessoal','1 hora',true,false,false,'','Muda sua aparência (incluindo equipamento) magicamente. Inspecionar revela a ilusão.',['Bardo','Feiticeiro','Mago']),
  s('Golpe Enredador',1,'Conjuração','1 ação bônus','Pessoal','Concentração, 1 min',true,false,false,'','Próximo acerto com arma: cipós brotam e o alvo TR Força ou fica imobilizado. 5 dano cortante/fogo destrói.',['Patrulheiro']),
  s('Emaranhar',1,'Conjuração','1 ação','27 metros','Concentração, 1 min',true,false,false,'','Plantas enredam criaturas num quadrado de 6m. TR Força ao entrar/começar turno ou fica imobilizado.',['Druida']),
  s('Retirada Rápida',1,'Transmutação','1 ação bônus','Pessoal','Concentração, 10 min',true,false,false,'','Por 10 minutos, você pode Correr como ação bônus em cada turno.',['Feiticeiro','Mago','Bruxo']),
  s('Fogo das Fadas',1,'Evocação','1 ação','18 metros','Concentração, 1 min',false,true,false,'','Objetos e criaturas em cubo de 4,5m ficam delineados em luz azul/verde/violeta. Ataques contra eles têm vantagem; não se beneficiam de invisibilidade.',['Bardo','Druida']),
  s('Vida Falsa',1,'Necromancia','1 ação','Pessoal','1 hora',true,false,true,'Um pouco de álcool e resíduo de açúcar','Ganha 1d4+4 PV temporários.',['Feiticeiro','Mago']),
  s('Queda em Plumas',1,'Transmutação','1 reação','18 metros','1 minuto',false,true,true,'Uma peninha ou pena de ganso','Reação à queda: queda reduzida a 18m/turno, sem dano de queda ao aterrissar.',['Bardo','Feiticeiro','Mago']),
  s('Encontrar Familiar',1,'Conjuração','1 hora (ritual)','3 metros','Instantâneo',true,false,true,'Incenso de 10 po + carvão, ervas, ouro em latão','Invoca familiar que serve como extensão seus sentidos.',['Mago']),
  s('Fruta Boa',1,'Transmutação','1 ação','Toque','Instantâneo',true,false,false,'','Até 10 bagas se tornam mágicas: cada uma cura 1 PV e fornece nutrição de um dia.',['Druida','Patrulheiro']),
  s('Graxa',1,'Conjuração','1 ação','18 metros','1 minuto',true,false,true,'Manteiga de porco','Área de 3m x 3m fica coberta de graxa escorregadia. TR Destreza ou cai prostrado ao entrar.',['Mago']),
  s('Dardo de Orientação',1,'Evocação','1 ação','36 metros','Instantâneo',true,false,false,'','Ataque mágico: 4d6 dano radiante. Alvo e todos a 1,5m têm desvantagem no próximo ataque (TR Sab anula).',['Clérico']),
  s('Palavra de Cura',1,'Evocação','1 ação bônus','18 metros','Instantâneo',true,false,false,'','Aliado recupera 1d4 + mod conjuração em PV.',['Bardo','Clérico','Druida']),
  s('Represália Infernal',1,'Evocação','1 reação','18 metros','Instantâneo',true,false,false,'','Reação ao ser atingido: 2d10 dano de fogo ao atacante (TR Destreza metade).',['Bruxo']),
  s('Heroísmo',1,'Encantamento','1 ação','Toque','Concentração, 1 min',true,false,false,'','Criatura torna-se imune a medo e ganha PV temporários iguais ao seu modificador de conjuração por turno.',['Bardo','Paladino']),
  s('Marca do Caçador',1,'Adivinhação','1 ação bônus','18 metros','Concentração, 1h',true,false,false,'','Marca um alvo. Causa 1d6 extra em ataques contra ele; vantagem em Percepção/Sobrevivência contra ele.',['Patrulheiro']),
  s('Faca de Gelo',1,'Conjuração','1 ação','18 metros','Instantâneo',false,true,true,'Uma gota de água','Arremessa faca de gelo: 1d10 perfurante no acerto; explode ao acertar causando 2d6 frio (TR Destreza).',['Druida','Feiticeiro','Mago']),
  s('Identificar',1,'Adivinhação','1 minuto (ritual)','Toque','Instantâneo',true,false,true,'Uma pérola de 100 po + pluma de coruja','Aprende as propriedades mágicas de um item ou magia que afeta uma criatura.',['Bardo','Mago']),
  s('Infligir Ferimentos',1,'Necromancia','1 ação','Toque','Instantâneo',true,false,false,'','Ataque de toque corpo a corpo: 3d10 dano necrótico. Não funciona em mortos-vivos e constructos.',['Clérico']),
  s('Salto',1,'Transmutação','1 ação','Toque','1 minuto',true,false,true,'Um grilo','Distância de salto triplicada por 1 minuto.',['Druida','Feiticeiro','Mago','Patrulheiro']),
  s('Passada Longa',1,'Transmutação','1 ação','Toque','1 hora',true,false,false,'','Velocidade da criatura aumenta em 3 metros por 1 hora.',['Bardo','Druida','Mago','Patrulheiro']),
  s('Armadura Mágica',1,'Abjuração','1 minuto','Toque','8 horas',true,false,true,'Couro curtido','Criatura sem armadura ganha CA 13 + mod Destreza.',['Mago']),
  s('Míssil Mágico',1,'Evocação','1 ação','36 metros','Instantâneo',true,false,false,'','Três dardos de força que acertam automaticamente. Cada um causa 1d4+1 dano de força.',['Feiticeiro','Mago']),
  s('Nuvem de Névoa',1,'Conjuração','1 ação','36 metros','Concentração, 1h',true,false,false,'','Esfera de névoa espessa de 6m de raio fortemente obscurece a área.',['Druida','Patrulheiro','Feiticeiro','Mago']),
  s('Proteção contra Mal e Bem',1,'Abjuração','1 ação','Toque','Concentração, 10 min',true,false,true,'Água benta ou pó de prata e ferro','Proteção contra aberrações, celestiais, elementais, fadas, demônios e mortos-vivos: desvantagem em ataques contra o alvo, não podem possuí-lo ou assustá-lo.',['Clérico','Druida','Paladino','Mago','Bruxo']),
  s('Proteção contra Veneno',1,'Abjuração','1 ação','Toque','1 hora',true,false,false,'','Vantagem em TRs contra veneno e resistência a dano de veneno. Neutraliza um veneno ativo.',['Clérico','Druida','Paladino','Patrulheiro']),
  s('Purificar Comida e Bebida',1,'Transmutação','1 ação (ritual)','3 metros','Instantâneo',true,false,false,'','Purifica toda comida e água não-mágica em esfera de 1,5m de raio, removendo venenos e doenças.',['Clérico','Druida','Paladino']),
  s('Raio de Doença',1,'Necromancia','1 ação','27 metros','Instantâneo',true,true,false,'','Ataque mágico: 2d8 dano de veneno. TR Constituição ou desvantagem em ataques até o fim do próximo turno.',['Feiticeiro','Mago']),
  s('Escudo',1,'Abjuração','1 reação','Pessoal','1 turno',false,true,false,'','Reação a ser atingido ou por Míssil Mágico: +5 CA e imunidade a Míssil Mágico até o início do próximo turno.',['Feiticeiro','Mago']),
  s('Escudo da Fé',1,'Abjuração','1 ação bônus','18 metros','Concentração, 10 min',true,false,true,'Um pergaminho sagrado','+2 CA a uma criatura de sua escolha.',['Clérico','Paladino']),
  s('Imagem Silenciosa',1,'Ilusão','1 ação','18 metros','Concentração, 10 min',true,false,true,'Um pouco de lã','Cria imagem visual de objeto, criatura ou fenômeno não maior que um cubo de 4,5m.',['Bardo','Feiticeiro','Mago']),
  s('Sono',1,'Encantamento','1 ação','27 metros','Instantâneo',true,false,true,'Pétalas de flores','5d8 PV de criaturas (mais fracas primeiro) adormecem por 1 minuto ou até receberem dano.',['Bardo','Feiticeiro','Mago']),
  s('Falar com Animais',1,'Adivinhação','1 ação (ritual)','Pessoal','10 minutos',true,false,false,'','Compreende e fala com bestas por 10 minutos.',['Bardo','Druida','Patrulheiro']),
  s('Bênção',1,'Encantamento','1 ação','9 metros','Concentração, 1 min',true,false,true,'Água benta','Até três criaturas adicionam 1d4 em jogadas de ataque e TRs.',['Clérico','Paladino']),
  s('Gargalhada Horrível de Tasha',1,'Encantamento','1 ação','9 metros','Concentração, 1 min',true,false,true,'Migalhas de torta','Humanoide TR Sabedoria ou fica prostrado e incapacitado de rir por 1 minuto.',['Bardo','Mago']),
  s('Golpe Trovejante',1,'Evocação','1 ação bônus','Pessoal','Concentração, 1 min',true,false,false,'','Próximo acerto com arma: 2d6 trovejante e alvo TR Força ou é empurrado 3m. Trovão audível 90m.',['Paladino']),
  s('Onda Trovejante',1,'Evocação','1 ação','Pessoal (cubo de 4,5m)','Instantâneo',true,false,false,'','TR Constituição ou 2d8 trovejante e empurrado 3m (metade em sucesso). Trovão audível 90m.',['Bardo','Druida','Feiticeiro','Mago','Patrulheiro']),
  s('Servo Invisível',1,'Conjuração','1 ação (ritual)','18 metros','1 hora',true,false,true,'Um pedaço de barbante, madeira e borracha','Força invisível não-inteligente executa tarefas simples (carregar, abrir, limpar). Força de 2.',['Bardo','Mago','Bruxo']),
  s('Raio Bruxa',1,'Evocação','1 ação','18 metros','Concentração, 1 min',true,false,false,'','Ataque mágico: 1d12 elétrico. Como ação, causa 1d12 automático se ainda conectado.',['Bruxo','Feiticeiro','Mago']),
  s('Golpe Furioso',1,'Evocação','1 ação bônus','Pessoal','Concentração, 1 min',true,false,false,'','Próximo acerto com arma: alvo TR Sab ou fica amedrontado até o fim de seu próximo turno.',['Paladino']),
  s('Maldição Sombria',1,'Encantamento','1 ação bônus','18 metros','Concentração, 1h',true,false,true,'Olho de víbora petrificado','Marca alvo: 1d6 extra de dano em ataques contra ele e vantagem em Percepção/Sobrevivência.',['Bruxo']),
  s('Localizar Animais',1,'Adivinhação','1 minuto (ritual)','Pessoal','Concentração, 1h',true,false,false,'','Detecta a presença de um tipo de animal em até 1,5 km.',['Bardo','Clérico','Druida','Paladino','Patrulheiro']),
];

// ─── Nível 2 ──────────────────────────────────────────────────────────────────
const LEVEL_2:DndSpellData[]=[
  s('Alterar-se',2,'Transmutação','1 ação','Pessoal','Concentração, 1h',true,false,false,'','Transforma sua aparência física: guelras, patas, pele dura, outros apêndices. CA 13 com pele natural.',['Feiticeiro','Mago']),
  s('Mensageiro Animal',2,'Encantamento','1 ação (ritual)','9 metros','24 horas',true,false,true,'Comida','Usa uma pequena besta como mensageiro para entregar mensagem de 25 palavras ao destinatário.',['Bardo','Druida','Patrulheiro']),
  s('Fechadura Arcana',2,'Abjuração','1 ação','Toque','Até ser dissipada',true,false,true,'Pó de ouro de 25 po','Tranca uma porta, janela ou baú. Só você (e quem designar) pode abrir sem Arrombamento (CD 25).',['Mago']),
  s('Agúrio',2,'Adivinhação','1 minuto (ritual)','Pessoal','Instantâneo',true,false,true,'Pedras de adivinhação','Pergunta sobre os resultados de uma ação específica nas próximas 30 min: bem-aventurado, adversidade, ambos ou nenhum.',['Clérico']),
  s('Cegueira/Surdez',2,'Necromancia','1 ação','9 metros','1 minuto',true,false,false,'','TR Constituição ou fica cego ou surdo (escolha). TR repetido no fim de cada turno.',['Bardo','Clérico','Feiticeiro','Mago']),
  s('Borrar',2,'Ilusão','1 ação','Pessoal','Concentração, 1 min',false,true,false,'','Seu corpo fica desfocado. Atacantes têm desvantagem em ataques contra você. Não funciona se cego.',['Feiticeiro','Mago']),
  s('Acalmar Emoções',2,'Encantamento','1 ação','18 metros','Concentração, 1 min',true,false,false,'','Suprime encantamento ou faz criaturas indiferentes a aliados e inimigos numa esfera de 6m.',['Bardo','Clérico']),
  s('Nuvem de Punhais',2,'Conjuração','1 ação','18 metros','Concentração, 1 min',true,false,false,'','Cubo de 1,5m de lâminas giratórias. Criatura que entre ou comece turno sofre 4d4 cortante.',['Bardo','Feiticeiro','Mago','Bruxo']),
  s('Chama Contínua',2,'Evocação','1 ação','Toque','Até ser dissipada',true,false,true,'Rubi de 50 po','Chama que não consome combustível e não apaga com vento ou água. Ilumina como tocha.',['Clérico','Mago']),
  s('Coroa da Loucura',2,'Encantamento','1 ação','18 metros','Concentração, 1 min',true,false,false,'','Humanoide TR Sab ou fica enfeitiçado e ataca alvo aleatório próximo. TR repetido a cada turno.',['Bardo','Feiticeiro','Mago','Bruxo']),
  s('Escuridão',2,'Evocação','1 ação','18 metros','Concentração, 10 min',true,false,true,'Gordura de morcego e alcatrão','Esfera de 4,5m de raio de escuridão mágica. Nenhuma visão funciona dentro.',['Bruxo','Feiticeiro','Mago']),
  s('Visão no Escuro',2,'Transmutação','1 ação','Toque','8 horas',true,false,true,'Cenoura seca e ágata','Criatura tocada ganha visão no escuro até 18m.',['Druida','Patrulheiro','Feiticeiro','Mago']),
  s('Detectar Pensamentos',2,'Adivinhação','1 ação','Pessoal','Concentração, 1 min',true,false,true,'Um cobre','Lê pensamentos superficiais de criaturas visíveis. Pode aprofundar (TR Sab para resistir).',['Bardo','Feiticeiro','Mago']),
  s('Sopro do Dragão',2,'Transmutação','1 ação bônus','Toque','Concentração, 1 min',true,false,true,'Uma pimenta vermelha','Criatura toca pode usar ação para soprar cone de 4,5m: ácido, frio, fogo, elétrico ou veneno (3d6, TR Dex).',['Feiticeiro','Mago']),
  s('Aprimorar Habilidade',2,'Transmutação','1 ação','Toque','Concentração, 1h',true,false,true,'Pelo ou pena de animal','Concede vantagem em todos os testes de um atributo à sua escolha.',['Bardo','Clérico','Druida','Feiticeiro','Mago']),
  s('Aumentar/Reduzir',2,'Transmutação','1 ação','9 metros','Concentração, 1 min',true,false,true,'Um pequeno pacote de pó de ferro','Aumenta ou reduz criatura/objeto ao dobro ou metade do tamanho. Afeta dados de dano, Força e CA.',['Bardo','Feiticeiro','Mago']),
  s('Fascinar',2,'Encantamento','1 ação','18 metros','Concentração, 1 min',true,false,false,'','Faz criaturas que ouvem você ficarem fascinadas. TR Sab ou desvantagem em Percepção de outros.',['Bardo','Bruxo']),
  s('Encontrar Corcel',2,'Conjuração','10 minutos','9 metros','Instantâneo',true,false,false,'','Invoca corcel mágico (cavaleiro, pégaso, etc.) que serve como companheiro montaria fiel.',['Paladino']),
  s('Lâmina de Chama',2,'Evocação','1 ação bônus','Pessoal','Concentração, 10 min',true,false,false,'','Espada de fogo na mão: ataque corpo a corpo, 3d6 fogo. Ilumina 3m de luz intensa.',['Druida']),
  s('Esfera Flamejante',2,'Conjuração','1 ação','18 metros','Concentração, 1 min',true,false,true,'Um pouco de sebo','Esfera de 1,5m de fogo: ataques a 1,5m sofrem 2d6 fogo (TR Dex). Pode ser rolada como ação bônus.',['Druida','Mago']),
  s('Rajada de Vento',2,'Evocação','1 ação','Pessoal (linha de 18m)','Concentração, 1 min',true,true,true,'Uma leguminosa','Linha de vento forte de 18m x 3m. Empurra criaturas e apaga chamas.',['Druida','Feiticeiro','Mago']),
  s('Aquecer Metal',2,'Transmutação','1 ação','18 metros','Concentração, 1 min',true,false,true,'Um pedaço de ferro e chama','Aquece metal fabricado: 2d8 fogo, e se continuar aquecendo o alvo pode largar o item ou ter desvantagem.',['Bardo','Druida']),
  s('Imobilizar Pessoa',2,'Encantamento','1 ação','18 metros','Concentração, 1 min',true,false,false,'','Humanoide TR Sab ou fica paralisado. TR repetido no fim de cada turno.',['Bardo','Clérico','Druida','Feiticeiro','Mago','Bruxo']),
  s('Invisibilidade',2,'Ilusão','1 ação','Toque','Concentração, 1h',true,false,true,'Um cílio coberto de cola','Criatura fica invisível. A magia termina se ela atacar ou conjurar.',['Bardo','Feiticeiro','Mago','Bruxo']),
  s('Abrir',2,'Transmutação','1 ação','18 metros','Instantâneo',true,false,false,'','Abre cadeado, porta, baú ou porta-portão de forma não-mágica. Falha se Fechadura Arcana (mas suprime por 10 min).',['Bardo','Feiticeiro','Mago']),
  s('Restauração Menor',2,'Abjuração','1 ação','Toque','Instantâneo',true,false,false,'','Remove uma doença, cegueira, surdez ou condição (paralisado, envenenado).',['Bardo','Clérico','Druida','Paladino','Patrulheiro']),
  s('Levitar',2,'Transmutação','1 ação','18 metros','Concentração, 10 min',true,false,true,'Pepita de ouro ou grão de areia','Criatura ou objeto (até 250 kg) flutua 6m no ar. Pode subir/descer como ação.',['Feiticeiro','Mago']),
  s('Localizar Objeto',2,'Adivinhação','1 ação','Pessoal','Concentração, 10 min',true,false,true,'Bifurcação de salgueiro','Detecta um objeto específico ou tipo de objeto em 90m.',['Bardo','Clérico','Druida','Paladino','Patrulheiro','Mago']),
  s('Arma Mágica',2,'Transmutação','1 ação bônus','Toque','Concentração, 1h',true,false,false,'','Transforma arma não-mágica em arma mágica +1.',['Paladino','Mago']),
  s('Espelho do Medo',2,'Ilusão','1 ação','18 metros','Concentração, 1 min',true,false,false,'','TR Sab ou fica amedrontado e deve fugir de você. TR repetido ao fim de cada turno.',['Bruxo']),
  s('Imagem Especular',2,'Ilusão','1 ação','Pessoal','1 minuto',true,false,false,'','Cria 3 duplicatas suas. Ataques têm 1/4 a 1/3 de chance de atingir duplicata (AC 10+Dex) em vez de você.',['Feiticeiro','Mago','Bruxo']),
  s('Passo de Névoa',2,'Conjuração','1 ação bônus','Pessoal','Instantâneo',false,true,false,'','Teletransporta até 9m para local visível.',['Feiticeiro','Mago','Bruxo','Paladino']),
  s('Raio de Lua',2,'Evocação','1 ação','45 metros','Concentração, 1 min',true,false,true,'Cristal de selenita','Cilindro de 1,5m de raio: 2d10 radiante ao entrar/começar turno (TR Constituição metade). Mortos-vivos e metamorfos têm desvantagem.',['Druida']),
  s('Passar sem Rastro',2,'Abjuração','1 ação','Pessoal','Concentração, 1h',true,false,false,'','Você e até 10 criaturas voluntárias ganham +10 em Furtividade e não podem ser rastreados por meios não-mágicos.',['Druida','Patrulheiro']),
  s('Força Fantasmagórica',2,'Ilusão','1 ação','18 metros','Concentração, 1 min',true,false,true,'Lã','Criatura TR Int ou acredita em ilusão como real. Ilusão pode causar 1d6 psíquico por turno.',['Bardo','Feiticeiro','Mago']),
  s('Prece de Cura',2,'Evocação','10 minutos','9 metros','Instantâneo',true,false,false,'','Até seis criaturas recuperam 2d8 + mod conjuração em PV.',['Clérico']),
  s('Raio Enfraquecedor',2,'Necromancia','1 ação','18 metros','Concentração, 1 min',true,false,false,'','Ataque mágico: 4d8 necrótico. Desvantagem em ataques baseados em Força enquanto concentrado.',['Bruxo','Feiticeiro','Mago']),
  s('Corda Mágica',2,'Transmutação','1 ação','18 metros','1 hora',true,false,true,'Corda de 1,5m ou mais','Corda se levanta até 18m. Quem suba entra em espaço extradimensional invisível (até 8 criaturas).',['Mago']),
  s('Ver Invisibilidade',2,'Adivinhação','1 ação','Pessoal','1 hora',true,false,true,'Uma pitada de talco e prata em pó','Veja criaturas e objetos invisíveis e no Plano Etéreo.',['Bardo','Feiticeiro','Mago']),
  s('Estilhaçar',2,'Evocação','1 ação','18 metros','Instantâneo',true,false,true,'Um fragmento de mica','TR Constituição ou 3d8 trovejante (metade em sucesso) em esfera de 3m. Objetos inanimados sofrem automaticamente.',['Bardo','Feiticeiro','Mago','Bruxo']),
  s('Silêncio',2,'Ilusão','1 ação (ritual)','45 metros','Concentração, 10 min',true,false,false,'','Esfera de silêncio de 6m de raio. Nenhum som entra/sai; magias com componente vocal não funcionam dentro.',['Bardo','Clérico','Patrulheiro']),
  s('Escalar como Aranha',2,'Transmutação','1 ação','Toque','Concentração, 1h',true,false,true,'Uma gota de asfalto e aranha','Criatura pode escalar superfícies verticais e tetos sem teste.',['Feiticeiro','Mago','Bruxo']),
  s('Crescimento de Espinhos',2,'Transmutação','1 ação','45 metros','Concentração, 10 min',false,true,false,'','Área de 6m de raio vira terreno difícil coberto de espinhos. 2d4 perfurante a cada 1,5m percorrido.',['Druida','Patrulheiro']),
  s('Arma Espiritual',2,'Evocação','1 ação bônus','18 metros','Concentração, 1 min',true,false,false,'','Arma espectral flutuante: ataque como ação bônus, 1d8+mod força. Pode ser movida 6m.',['Clérico']),
  s('Sugestão',2,'Encantamento','1 ação','9 metros','Concentração, 8h',true,false,true,'Língua de cobra e mel','Criatura TR Sab ou segue sugestão razoável de 1-2 frases por 8 horas.',['Bardo','Feiticeiro','Mago','Bruxo']),
  s('Casca de Árvore',2,'Transmutação','1 ação','Toque','Concentração, 1h',true,false,true,'Punhado de casca de carvalho','CA torna-se 16 (se não for maior). Não requer armadura.',['Druida']),
  s('Vínculo de Guarda',2,'Abjuração','1 ação','Toque','1 hora',true,false,true,'Uma faixa de pano','Ligue dois alvos: enquanto a 18m, o alvo protegido tem resistência a todo dano, mas você sofre o mesmo dano.',['Clérico']),
  s('Teia',2,'Conjuração','1 ação','18 metros','Concentração, 1h',true,false,true,'Um pouco de teia de aranha','Cubo de 6m de teias. Criaturas TR Destreza ou ficam retidas. TR Força para escapar.',['Feiticeiro','Mago']),
  s('Zona de Verdade',2,'Encantamento','1 ação','18 metros','10 minutos',true,false,false,'','Esfera de 4,5m: criaturas que falharem TR Carisma não podem mentir conscientemente.',['Bardo','Clérico','Paladino']),
  s('Flecha Ácida',2,'Evocação','1 ação','27 metros','Instantâneo',true,false,true,'Pó de ruibarbo e víbora de lama','Ataque mágico: 4d4 ácido + 2d4 ácido no início do próximo turno.',['Mago']),
  s('Espinhos',2,'Transmutação','1 ação','45 metros','Concentração, 10 min',false,true,true,'Sete espinhos afiados','Espinhos brotam num raio de 6m. Terreno difícil; 2d4 perfurante ao atravessar.',['Druida','Patrulheiro']),
  s('Auxílio',2,'Abjuração','1 ação','Toque','8 horas',true,false,true,'Uma fita de pano branco','Até três criaturas ganham +5 PV máximos e atuais.',['Clérico','Paladino']),
  s('Invisibilidade Menor',2,'Ilusão','1 ação','Toque','1 hora',true,false,true,'Pano de manto de invisibilidade','Você ou criatura tocada fica invisível. A magia NÃO termina ao atacar ou conjurar.',['Mago']),
];

// ─── Nível 3 ──────────────────────────────────────────────────────────────────
const LEVEL_3:DndSpellData[]=[
  s('Animar Mortos',3,'Necromancia','1 minuto','3 metros','Instantâneo',true,false,true,'Uma gota de sangue e um pouco de terra e osso','Cria um esqueleto ou zumbi de restos mortais num raio de 3m. Obedece seus comandos por 24h (renove com a magia).',['Clérico','Mago']),
  s('Farol de Esperança',3,'Abjuração','1 ação','9 metros','Concentração, 1 min',true,false,false,'','Até três criaturas têm vantagem em TRs de Sabedoria e Morte, e curas máximas se aplicam a elas.',['Clérico']),
  s('Impor Maldição',3,'Necromancia','1 ação','Toque','Concentração, 1 min',true,false,false,'','Toque: amaldiçoa. Escolha: desvantagem em um atributo; desvantagem em ataques contra você; TR Sab a cada turno ou perda de ação; ou 1d8 extra em ataques.',['Bardo','Clérico','Mago']),
  s('Piscar',3,'Transmutação','1 ação','Pessoal','1 minuto',true,false,false,'','No fim de cada turno, role 1d20: 11+ = você vai ao Plano Etéreo até o início do próximo turno.',['Feiticeiro','Mago']),
  s('Bola de Fogo',3,'Evocação','1 ação','45 metros','Instantâneo',true,false,true,'Guano de morcego e enxofre','8d6 de fogo em esfera de 6m de raio (TR Destreza metade).',['Feiticeiro','Mago']),
  s('Chamado do Relâmpago',3,'Conjuração','1 ação','36 metros','Concentração, 10 min',true,false,false,'','Nuvem de 18m de raio. Como ação, raio cai: 3d10 elétrico (TR Dex metade) a criaturas em 1,5m do ponto.',['Druida']),
  s('Clarividência',3,'Adivinhação','10 minutos','2 km','Concentração, 10 min',true,false,true,'Espelho/cristal de 100 po','Cria sensor invisível num local que você conheça. Você vê ou ouve através dele.',['Bardo','Clérico','Feiticeiro','Mago']),
  s('Convocar Animais',3,'Conjuração','1 ação','18 metros','Concentração, 1h',true,false,false,'','Evoca espíritos como bestas: 1 CR 2, 2 CR 1, 4 CR 1/2 ou 8 CR 1/4. Obedecem seus comandos.',['Druida','Patrulheiro']),
  s('Salva de Projéteis',3,'Conjuração','1 ação','Pessoal (cone de 18m)','Instantâneo',true,false,true,'Uma munição','Cone de projéteis: 3d8 dano da arma (TR Dex metade).',['Patrulheiro']),
  s('Contrafeitiço',3,'Abjuração','1 reação','18 metros','Instantâneo',false,true,false,'','Cancela magia sendo conjurada. Nível 3 ou menor: automático. Acima: teste de habilidade CD 10+nível.',['Feiticeiro','Mago','Bruxo']),
  s('Criar Comida e Água',3,'Conjuração','1 ação','9 metros','Instantâneo',true,false,false,'','Cria 45 kg de comida e 120 litros de água limpa (sustenta 15 humanoides e 5 montarias por 24h).',['Clérico','Paladino']),
  s('Luz do Dia',3,'Evocação','1 ação','18 metros','1 hora',true,false,false,'','Luz de 18m de raio (como luz do dia). Pode ser colocada em objeto. Dispersa trevas mágicas de nível 3 ou menor.',['Clérico','Druida','Paladino','Patrulheiro','Feiticeiro']),
  s('Dissolver Magia',3,'Abjuração','1 ação','27 metros','Instantâneo',true,false,false,'','Termina um efeito mágico no alvo. Nível 3 ou menor: automático. Acima: teste de habilidade.',['Bardo','Clérico','Druida','Paladino','Patrulheiro','Feiticeiro','Mago','Bruxo']),
  s('Arma Elemental',3,'Transmutação','1 ação bônus','Toque','Concentração, 1h',true,false,false,'','Transforma arma não-mágica em +1 que causa 1d4 extra de ácido/frio/fogo/elétrico/trovejante.',['Paladino']),
  s('Medo',3,'Ilusão','1 ação','Pessoal (cone de 9m)','Concentração, 1 min',true,false,false,'','Criatura no cone TR Sab ou fica amedrontada e deve fugir. TR repetido se sair de visão.',['Bardo','Feiticeiro','Mago','Bruxo']),
  s('Forma Gasosa',3,'Transmutação','1 ação','Toque','Concentração, 1h',true,false,true,'Um pouco de fumaça','Criatura se transforma em nuvem gasosa: resistência a dano não-mágico, pode entrar por pequenas frestas.',['Feiticeiro','Mago','Bruxo']),
  s('Glifo de Proteção',3,'Abjuração','1 hora','Toque','Até ser acionado',true,false,true,'Incenso e diamante em pó de 200 po','Glifo mágico: quando acionado, explode (5d8 de energia, esfera de 6m) ou libera magia de nível ≤3.',['Bardo','Clérico','Mago']),
  s('Pressa',3,'Transmutação','1 ação','9 metros','Concentração, 1 min',true,false,true,'Um pêlo de alcaçuz','Criatura duplica velocidade, +2 CA, vantagem em TR Destreza e uma ação adicional (só ataque, Correr, Retirar, Esconder ou Usar Objeto) por turno.',['Druida','Feiticeiro','Mago']),
  s('Padrão Hipnótico',3,'Ilusão','1 ação','36 metros','Concentração, 1 min',false,true,true,'Uma vareta de incenso brilhante','Criaturas num cubo de 9m TR Sab ou ficam incapacitadas e fascinadas. Aliado pode sacudir com uma ação.',['Bardo','Feiticeiro','Mago','Bruxo']),
  s('Raio',3,'Evocação','1 ação','27 metros','Instantâneo',true,false,true,'Pele de morcego e âmbar','Raio de 30m: 8d6 elétrico (TR Destreza metade) em toda a linha.',['Feiticeiro','Mago']),
  s('Cabana de Leomund',3,'Evocação','1 minuto (ritual)','Pessoal','8 horas',true,true,false,'','Cria domo opaco de 3m de raio. Temperatura agradável, não-hostis não podem entrar.',['Bardo','Mago']),
  s('Imagem Maior',3,'Ilusão','1 ação','36 metros','Concentração, 10 min',true,false,true,'Pó de mica','Ilusão de som, imagem, cheiro de objeto/criatura até cubo de 6m. Pode ser animada.',['Bardo','Feiticeiro','Mago','Bruxo']),
  s('Círculo Mágico',3,'Abjuração','1 minuto','10 metros','1 hora',true,false,true,'Água benta/pó de prata de 100 po, consumidos','Círculo de 3m de raio que bloqueia ou aprisiona aberrações, celestiais, elementais, fadas ou mortos-vivos.',['Clérico','Paladino','Mago','Bruxo']),
  s('Palavra de Cura em Massa',3,'Evocação','1 ação bônus','18 metros','Instantâneo',true,false,false,'','Até seis criaturas recuperam 1d4 + mod conjuração em PV.',['Clérico']),
  s('Não-Detecção',3,'Abjuração','1 ação','Toque','8 horas',true,false,true,'Pó de diamante de 25 po','Uma criatura ou objeto fica invisível a magias de adivinhação e visão especial.',['Bardo','Patrulheiro','Mago']),
  s('Corcel Fantasma',3,'Ilusão','1 minuto (ritual)','9 metros','1 hora',true,false,false,'','Cria corcel ilusório (velocidade 30m e de marcha 240m) para uma criatura montar.',['Mago']),
  s('Crescimento de Plantas',3,'Transmutação','1 ação ou 8h','27 metros','Instantâneo',true,false,false,'','Toda vegetação numa área de 30m de raio torna-se exuberante e densa (terreno difícil). Ou faz crescer numa noite.',['Bardo','Druida','Patrulheiro']),
  s('Proteção contra Energia',3,'Abjuração','1 ação','Toque','Concentração, 1h',true,false,false,'','Criatura ganha resistência a um tipo de dano (ácido, frio, fogo, elétrico ou trovejante).',['Clérico','Druida','Patrulheiro','Feiticeiro','Mago']),
  s('Remover Maldição',3,'Abjuração','1 ação','Toque','Instantâneo',true,false,false,'','Termina todas as maldições na criatura ou objeto tocado.',['Clérico','Paladino','Mago','Bruxo']),
  s('Revivificar',3,'Necromancia','1 ação','Toque','Instantâneo',true,false,true,'Diamantes de 300 po, consumidos','Restaura criatura que morreu no último minuto com 1 PV.',['Clérico','Paladino']),
  s('Enviar Mensagem',3,'Evocação','1 ação','Ilimitado','1 rodada',true,false,true,'Fio de cobre fino','Envia mensagem telepática de 25 palavras a criatura conhecida. Ela pode responder com 25 palavras.',['Bardo','Clérico','Mago']),
  s('Guardiões Espirituais',3,'Conjuração','1 ação','Pessoal (4,5m de raio)','Concentração, 10 min',true,false,true,'Um símbolo sagrado','Espíritos protegem área ao redor: velocidade reduzida à metade, 3d8 radiante/necrótico ao entrar/começar turno (TR Sab metade).',['Clérico']),
  s('Tempestade de Gelo',3,'Conjuração','1 ação','90 metros','Instantâneo',true,false,true,'Pó de água e gelo','Cilindro de 6m de raio: 2d8 frio + 4d6 contundente (TR Dex metade do frio). Terreno difícil por 1 turno.',['Druida','Mago','Feiticeiro']),
  s('Tempestade de Granizo',3,'Conjuração','1 ação','90 metros','Concentração, 1 min',true,false,false,'','Cilindro de 18m de raio de granizo e chuva. Fortemente obscurecido, terreno difícil.',['Druida','Feiticeiro','Mago']),
  s('Lentidão',3,'Transmutação','1 ação','36 metros','Concentração, 1 min',true,false,true,'Melaço','Até seis criaturas TR Sab ou ficam lentas: velocidade na metade, -2 CA, -2 TR Destreza, sem reação.',['Feiticeiro','Mago']),
  s('Falar com Mortos',3,'Necromancia','1 ação','3 metros','10 minutos',true,false,true,'Erva de crisântemo','Faz cadáver responder até 5 perguntas com conhecimento que tinha em vida.',['Bardo','Clérico']),
  s('Falar com Plantas',3,'Transmutação','1 ação','Pessoal','10 minutos',true,false,false,'','Pode questionar e dar ordens básicas a plantas. Elas respondem o melhor que podem.',['Bardo','Druida','Patrulheiro']),
  s('Nuvem Fétida',3,'Conjuração','1 ação','27 metros','Concentração, 1 min',true,false,true,'Um ovo podre','Esfera de 6m de nuvem nausêante. TR Constituição ou passa a ação enjoado/inconsciente.',['Bardo','Feiticeiro','Mago']),
  s('Passo Trovejante',3,'Conjuração','1 ação','Pessoal','Instantâneo',true,false,false,'','Teletransporta até 27m; trovão de 1,5m no ponto de saída (3d10 elétrico, TR Dex).',['Feiticeiro','Mago','Bruxo']),
  s('Línguas',3,'Adivinhação','1 ação','Toque','1 hora',true,false,true,'Uma estatueta de argila de Hermes','Criatura compreende e fala qualquer idioma por 1 hora.',['Bardo','Clérico','Feiticeiro','Mago','Bruxo']),
  s('Toque Vampírico',3,'Necromancia','1 ação','Pessoal','Concentração, 1 min',true,false,false,'','Ataque de toque: 3d6 necrótico. Recupera metade do dano como PV. Pode repetir a cada turno.',['Mago','Bruxo']),
  s('Respirar Água',3,'Transmutação','1 ação (ritual)','Toque','24 horas',true,false,true,'Uma gota d\'água','Até 10 criaturas respiram debaixo d\'água. Criaturas que normalmente respiram água podem respirar ar.',['Druida','Patrulheiro','Feiticeiro','Mago']),
  s('Andar na Água',3,'Transmutação','1 ação (ritual)','9 metros','1 hora',true,false,false,'','Até 10 criaturas caminham sobre líquidos como se fosse terreno sólido.',['Clérico','Druida','Patrulheiro']),
  s('Flecha Relâmpago',3,'Transmutação','1 ação bônus','Pessoal','Concentração, 1 min',true,false,false,'','Próximo acerto com arma de alcance: 4d8 elétrico extra; criaturas a 3m do alvo: 2d8 elétrico (TR Dex).',['Patrulheiro']),
  s('Infligir Ferimentos grave',3,'Necromancia','1 ação','Toque','Instantâneo',true,false,false,'','Ataque de toque: 6d10 dano necrótico. Não funciona em mortos-vivos e constructos. (Upcast de Infligir Ferimentos 3°)',['Clérico']),
];

// ─── Nível 4 ──────────────────────────────────────────────────────────────────
const LEVEL_4:DndSpellData[]=[
  s('Olho Arcano',4,'Adivinhação','1 ação','9 metros','Concentração, 1h',true,false,false,'','Cria olho mágico invisível que você controla (9m visão, 9m escuridão). Pode mover 9m por ação.',['Mago']),
  s('Banimento',4,'Abjuração','1 ação','18 metros','Concentração, 1 min',true,false,true,'Um item avesso ao alvo','TR Carisma ou criatura é banida para outro plano. Concentração mantida = banimento permanente.',['Clérico','Paladino','Feiticeiro','Mago','Bruxo']),
  s('Peste',4,'Necromancia','1 ação','9 metros','Instantâneo',true,false,false,'','TR Constituição ou 8d8 necrótico (metade em sucesso). Drena vida.',['Druida','Patrulheiro','Feiticeiro','Mago','Bruxo']),
  s('Compulsão',4,'Encantamento','1 ação','9 metros','Concentração, 1 min',true,false,false,'','Até quatro criaturas que ouvir TR Sab ou agem de acordo com sua instrução (dançar, aproximar-se, etc.).',['Bardo']),
  s('Confusão',4,'Encantamento','1 ação','27 metros','Concentração, 1 min',true,false,true,'Três nozes','Criaturas num cubo de 3m TR Sab ou ficam confusas: agem aleatoriamente (rolar d10 por turno).',['Bardo','Druida','Feiticeiro','Mago']),
  s('Convocar Seres da Floresta',4,'Conjuração','1 ação','18 metros','Concentração, 1h',true,false,true,'Um presente para fadas','Evoca fadas: 1 CR 2, 2 CR 1, 4 CR 1/2 ou 8 CR 1/4. Obedecem seus comandos.',['Druida','Patrulheiro']),
  s('Controlar Água',4,'Transmutação','1 ação','90 metros','Concentração, 10 min',true,false,true,'Pó de terra e água','Manipula corpos de água: inundar, drenar, turbulência, remoinho. Criaturas TR Força.',['Clérico','Druida','Mago']),
  s('Proteção da Morte',4,'Abjuração','1 ação','Toque','8 horas',true,false,false,'','Primeira vez que chegar a 0 PV, vai para 1 PV em vez disso.',['Clérico','Paladino']),
  s('Porta Dimensional',4,'Conjuração','1 ação','150 metros','Instantâneo',true,false,false,'','Teletransporte imediato até 150m para local que você veja ou descreva. Pode levar criatura.',['Bardo','Feiticeiro','Mago','Bruxo']),
  s('Adivinhação',4,'Adivinhação','1 ação (ritual)','Pessoal','Instantâneo',true,false,true,'Incenso e oferta de 25 po, consumidos','Faz pergunta sobre eventos das próximas 7 dias e recebe resposta verdadeira (embora críptica).',['Clérico']),
  s('Dominar Besta',4,'Encantamento','1 ação','18 metros','Concentração, 1 min',true,false,false,'','Besta TR Sab ou fica sob seu controle telepático. TR repetido a cada turno.',['Druida','Patrulheiro','Feiticeiro']),
  s('Tentáculos Negros',4,'Conjuração','1 ação','27 metros','Concentração, 1 min',true,false,false,'','Tentáculos num quadrado de 6m: terreno difícil, criaturas TR Destreza ou ficam retidas (3d6 contundente/turno).',['Mago']),
  s('Fabricar',4,'Transmutação','10 minutos','36 metros','Instantâneo',true,false,false,'','Transforma matéria-prima em produto acabado (não-mágico). Até 1,8m³ de madeira ou 0,6m³ de metal.',['Mago']),
  s('Escudo de Fogo',4,'Evocação','1 ação','Pessoal','10 minutos',true,false,false,'','Chamas ao redor: resistência a frio ou fogo, e atacantes a 1,5m sofrem 2d8 do tipo oposto.',['Mago']),
  s('Liberdade de Movimento',4,'Abjuração','1 ação','Toque','1 hora',true,false,true,'Uma faixa de couro','Ignora terreno difícil, magia que reduza velocidade, e pode escapar de aprisionar de forma não-mágica.',['Bardo','Clérico','Druida','Paladino','Patrulheiro']),
  s('Cipó Agarrador',4,'Conjuração','1 ação bônus','18 metros','Concentração, 1 min',true,false,false,'','Um cipó emerge e ataca criatura em 9m: TR Destreza ou fica retida. Como ação bônus, pode mudar alvo.',['Druida','Patrulheiro']),
  s('Grande Invisibilidade',4,'Ilusão','1 ação','Toque','Concentração, 1 min',true,false,false,'','Invisibilidade que NÃO termina ao atacar ou conjurar.',['Bardo','Feiticeiro','Mago','Bruxo']),
  s('Guardiã da Fé',4,'Conjuração','1 ação','9 metros','8 horas',true,false,false,'','Guardião de 3m aparece: criaturas hostis a 3m TR Destreza ou 20 radiante. Desaparece após 60 de dano total.',['Clérico']),
  s('Terreno Alucinatório',4,'Ilusão','10 minutos','90 metros','24 horas',true,true,true,'Pedra, ramo e pó de folha verde','Transforma aparência de terreno natural numa área de 45m de cubo.',['Bardo','Druida','Mago','Bruxo']),
  s('Localizar Criatura',4,'Adivinhação','1 ação','Pessoal','Concentração, 1h',true,false,true,'Pelo da criatura','Detecta a criatura/tipo escolhido em 90m (ou 450m se for o mesmo tipo de criatura).',['Bardo','Clérico','Druida','Paladino','Patrulheiro','Mago']),
  s('Assassino Fantasmal',4,'Ilusão','1 ação','36 metros','Concentração, 1 min',true,false,false,'','TR Sab ou criatura fica amedrontada. Enquanto amedrontada: 4d10 psíquico por turno (TR Sab anula). Se cair a 0, morre de medo.',['Mago']),
  s('Polimorfar',4,'Transmutação','1 ação','18 metros','Concentração, 1h',false,true,true,'Um casulo de lagarta','Transforma criatura em besta (CR ≤ nível/4 ou original). PV da nova forma. Volta a 0 PV.',['Bardo','Druida','Feiticeiro','Mago']),
  s('Esfera Resiliente',4,'Evocação','1 ação','18 metros','Concentração, 1 min',true,false,true,'Um hemisfério de cristal e outro de goma','Esfera de força imune a todo dano aprisiona criatura. Não pode ser empurrada ou teleportada.',['Mago']),
  s('Dar Forma à Pedra',4,'Transmutação','1 ação','Toque','Instantâneo',false,true,false,'','Molda pedra em qualquer forma (cubo de 1,5m). Pode criar passagens ou selar portas.',['Clérico','Druida','Mago']),
  s('Pele de Pedra',4,'Abjuração','1 ação','Toque','Concentração, 1h',true,false,true,'Pó de diamante de 100 po','Criatura ganha resistência a dano não-mágico de arma.',['Druida','Patrulheiro','Feiticeiro','Mago']),
  s('Muro de Fogo',4,'Evocação','1 ação','36 metros','Concentração, 1 min',true,false,true,'Um pouco de fósforo','Muro de fogo de até 18m de comprimento. 5d8 fogo ao atravessar ou começar turno dentro (TR Dex metade).',['Druida','Feiticeiro','Mago']),
];

// ─── Nível 5 ──────────────────────────────────────────────────────────────────
const LEVEL_5:DndSpellData[]=[
  s('Animar Objetos',5,'Transmutação','1 ação','36 metros','Concentração, 1 min',true,false,false,'','Anima até 10 objetos pequenos (ou menos maiores). Cada objeto age como criatura seguindo seus comandos.',['Bardo','Feiticeiro','Mago']),
  s('Barreira Anti-Vida',5,'Abjuração','1 ação','Pessoal','Concentração, 1h',true,false,false,'','Barreira de força em 3m de raio impede criaturas vivas (não-mortos-vivos/constructos) de entrar.',['Druida']),
  s('Despertar',5,'Transmutação','8 horas','Toque','Instantâneo',true,false,true,'Ágata de 1.000 po, consumida','Concede consciência e Int 10 a planta ou besta com Int 3 ou menos. Fala um idioma seu.',['Bardo','Druida']),
  s('Golpe Banidor',5,'Abjuração','1 ação bônus','Pessoal','Concentração, 1 min',true,false,false,'','Próximo acerto com arma: 5d10 dano de força. Se reduzir a 0 PV, bane a criatura para plano de origem.',['Paladino']),
  s('Círculo de Poder',5,'Abjuração','1 ação','Pessoal','Concentração, 10 min',true,false,false,'','Aura de 9m de raio: aliados têm vantagem em TRs contra magia; em sucesso, sofrem metade do dano.',['Paladino']),
  s('Nuvem Mortífera',5,'Conjuração','1 ação','36 metros','Concentração, 10 min',true,false,false,'','Esfera de 6m de nuvem venenosa. 5d8 veneno ao entrar/começar turno (TR Constituição metade).',['Feiticeiro','Mago']),
  s('Comunhão',5,'Adivinhação','1 minuto (ritual)','Pessoal','1 minuto',true,false,true,'Incenso e oferenda de libação','Contata sua divindade para até 3 perguntas de sim/não sobre eventos das próximas 7 dias.',['Clérico']),
  s('Comunhão com a Natureza',5,'Adivinhação','1 minuto (ritual)','Pessoal','Instantâneo',true,false,false,'','Em florestas/natureza, aprende até 3 fatos sobre território em 4,5 km (criatura, terreno, etc.).',['Druida','Patrulheiro']),
  s('Cone de Frio',5,'Evocação','1 ação','Pessoal (cone de 18m)','Instantâneo',true,false,false,'','8d8 de frio em cone de 18m (TR Constituição metade). Criaturas mortas viram estátuas de gelo.',['Feiticeiro','Mago']),
  s('Convocar Elemental',5,'Conjuração','1 minuto','18 metros','Concentração, 1h',true,false,true,'Pedra/água/ar/fogo','Convoca elemental CR 5 de terra, água, ar ou fogo que obedece seus comandos.',['Druida','Mago']),
  s('Contágio',5,'Necromancia','1 ação','Toque','7 dias',true,false,false,'','Toque: após 3 falhas em TRs Constituição (acumuláveis), criatura fica gravemente doente (Carne Podre, Febre dos Olhos, etc.).',['Clérico','Druida']),
  s('Criação',5,'Ilusão','1 minuto','9 metros','Especial',true,false,true,'Pó de ouro de 20 po','Cria objeto inanimado de material de Sombra. Dura de 1 min (ferro) a 1 dia (madeira).',['Bardo','Feiticeiro','Mago']),
  s('Onda Destrutiva',5,'Evocação','1 ação','Pessoal','Instantâneo',true,false,false,'','Onda de 9m de raio: TR Constituição ou 5d6 trovejante + 5d6 radiante/necrótico e fica prostrado.',['Paladino']),
  s('Dissipar Mal e Bem',5,'Abjuração','1 ação','Pessoal','Concentração, 1 min',true,false,true,'Água benta e pó de prata e ferro','Aura proteção contra celestiais, elementais, fadas, demônios, mortos-vivos. Pode banir ou quebrar encantamento.',['Clérico','Paladino']),
  s('Golpe de Chama',5,'Evocação','1 ação','18 metros','Instantâneo',true,false,false,'','Coluna de luz divina de 3m de raio: 4d6 fogo + 4d6 radiante (TR Dex metade).',['Clérico']),
  s('Geas',5,'Encantamento','1 minuto','18 metros','30 dias',true,false,false,'','Encanta criatura que possa ouvir e entender você para executar (ou evitar) uma tarefa. 5d10 psíquico/dia se desobedecer.',['Bardo','Clérico','Druida','Paladino','Mago']),
  s('Restauração Maior',5,'Abjuração','1 ação','Toque','Instantâneo',true,false,true,'Pó de diamante de 100 po','Remove encantamento, maldição, redução de atributo, exaustão ou petrificação.',['Bardo','Clérico','Druida']),
  s('Santificar',5,'Evocação','24 horas','Toque','Até ser dissipada',true,false,true,'Ervas, óleo, incenso de 1.000 po','Santifica área de 18m de raio. Previne teletransporte, bola cristal, restringe tipos de criaturas.',['Clérico']),
  s('Imobilizar Monstro',5,'Encantamento','1 ação','18 metros','Concentração, 1 min',true,false,false,'','Qualquer criatura (exceto mortos-vivos) TR Sab ou fica paralisada. TR repetido a cada turno.',['Bardo','Feiticeiro','Mago','Bruxo']),
  s('Praga de Insetos',5,'Conjuração','1 ação','90 metros','Concentração, 10 min',true,false,true,'Um punhado de açúcar, insetos e gordura animal','Esfera de 6m de raio de gafanhotos: 4d10 perfurante ao entrar/começar turno (TR Constituição metade).',['Clérico','Druida','Feiticeiro']),
  s('Lore das Lendas',5,'Adivinhação','10 minutos','Pessoal','Instantâneo',true,false,true,'Incenso de 250 po + ramos de azevinho, consumidos','Aprende informações sobre uma pessoa, lugar, objeto ou evento de importância histórica.',['Bardo','Clérico','Mago']),
  s('Cura Ferimentos em Massa',5,'Evocação','1 ação','18 metros','Instantâneo',true,false,false,'','Onda de cura: até seis criaturas recuperam 3d8 + mod conjuração em PV.',['Bardo','Clérico','Druida']),
  s('Enganar',5,'Ilusão','1 ação','Pessoal','Concentração, 1h',false,true,false,'','Torna-se invisível e cria duplicata ilusória de si mesmo. Pode ver através da duplicata.',['Bardo','Mago']),
  s('Modificar Memória',5,'Encantamento','1 ação','9 metros','Concentração, 1 min',true,false,false,'','TR Sab ou fica incapacitado. Pode modificar sua memória das últimas 24h. Após 1 min, nova memória é implantada.',['Bardo','Mago']),
  s('Passagem nas Paredes',5,'Transmutação','1 ação','9 metros','1 hora',true,false,true,'Gergelim e um pouco de terra','Cria passagem de 1,5m de largura numa parede de até 3m de espessura.',['Mago']),
  s('Ressuscitar',5,'Necromancia','1 hora','Toque','Instantâneo',true,false,true,'Diamante de 500 po, consumido','Traz de volta criatura morta há até 10 dias com 1 PV. Criatura sofre penalidade por alguns dias.',['Bardo','Clérico','Paladino']),
  s('Reencarnar',5,'Transmutação','1 hora','Toque','Instantâneo',true,false,true,'Óleos e unguentos de 1.000 po','Traz de volta criatura morta há até 10 dias em corpo de nova raça.',['Druida']),
  s('Espiritismo',5,'Adivinhação','10 minutos','Pessoal','Concentração, 10 min',true,false,true,'Espelho de pedraria de 1.000 po','Veja e ouça criatura específica em qualquer plano (TR Sab para resistir).',['Bardo','Clérico','Druida','Mago','Bruxo']),
  s('Parecer',5,'Ilusão','1 ação','9 metros','8 horas',true,false,false,'','Transforma aparência de qualquer número de criaturas em qualquer forma que você escolha.',['Bardo','Feiticeiro','Mago']),
  s('Aljava Veloz',5,'Transmutação','1 ação bônus','Pessoal','Concentração, 1 min',true,false,true,'Aljava com flechas/virotes','A aljava produz novas munições infinitamente; você pode fazer dois ataques adicionais com ação bônus.',['Patrulheiro']),
  s('Estática Sináptica',5,'Encantamento','1 ação','36 metros','Instantâneo',true,false,false,'','TR Int ou 8d6 psíquico e subtrai 1d6 de jogadas de ataque/verificação/concentração por 1 minuto.',['Bardo','Feiticeiro','Mago','Bruxo']),
  s('Telecinesia',5,'Transmutação','1 ação','18 metros','Concentração, 10 min',true,false,false,'','Move objeto/criatura (até 500 kg / TR Força). Pode apertar criaturas causando 2d6/turno.',['Feiticeiro','Mago']),
  s('Círculo de Teletransporte',5,'Conjuração','1 minuto','3 metros','1 rodada',true,false,true,'Calcário, carvão e sangue de 50 po','Abre portal para círculo permanente que você conheça em outro local.',['Bardo','Feiticeiro','Mago']),
  s('Passo Arbóreo',5,'Conjuração','1 ação','Pessoal','Concentração, 1 min',true,false,false,'','Entre em árvore e saia de qualquer outra árvore do mesmo tipo em 90m.',['Clérico','Druida','Patrulheiro']),
  s('Muro de Força',5,'Evocação','1 ação','36 metros','Concentração, 10 min',false,true,true,'Pó de diamante de 5 po','Cria painel plano de força (10m x 10m, 6mm) invulnerável a todo dano.',['Mago']),
  s('Muro de Pedra',5,'Evocação','1 ação','36 metros','Concentração, 10 min',true,false,true,'Granito pequeno','Cria muro de até dez painéis de 3m x 3m ou 5 painéis de 3m x 6m de pedra sólida.',['Clérico','Druida','Feiticeiro','Mago']),
];

// ─── Nível 6 ──────────────────────────────────────────────────────────────────
const LEVEL_6:DndSpellData[]=[
  s('Portal Arcano',6,'Conjuração','1 ação','36 metros','Concentração, 10 min',true,false,false,'','Cria dois portais conectados de 2m de altura em locais que você veja dentro do alcance.',['Feiticeiro','Mago','Bruxo']),
  s('Barreira de Lâminas',6,'Conjuração','1 ação','27 metros','Concentração, 10 min',true,false,false,'','Muro de 18m x 3m de lâminas giratórias: 6d10 cortante ao atravessar (TR Destreza metade).',['Clérico']),
  s('Corrente de Relâmpagos',6,'Evocação','1 ação','30 metros','Instantâneo',true,false,true,'Bastão de âmbar de 1.500 po','Relâmpago salta por até 3 alvos: primeiro sofre 10d8 elétrico (TR Dex metade), demais metade.',['Druida','Feiticeiro','Mago']),
  s('Círculo de Morte',6,'Necromancia','1 ação','45 metros','Instantâneo',true,false,true,'Pó de osso de 500 po','Esfera de 18m de raio: TR Constituição ou 8d6 necrótico (metade em sucesso).',['Feiticeiro','Mago','Bruxo']),
  s('Convocar Fada',6,'Conjuração','1 minuto','18 metros','Concentração, 1h',true,false,true,'Um galho de carvalho ou azevinho','Convoca fada de CR 6 ou menor que obedece seus comandos.',['Druida','Bruxo']),
  s('Criar Morto-Vivo',6,'Necromancia','1 minuto','3 metros','Instantâneo',true,false,true,'Um caixão de argila de 150 po','Cria ghoul, ghast ou wight de restos mortais que obedece seus comandos.',['Clérico','Mago','Bruxo']),
  s('Desintegrar',6,'Transmutação','1 ação','18 metros','Instantâneo',true,false,true,'Magnetita e mercúrio em pó','TR Destreza ou 10d6+40 dano de força. A 0 PV, criatura é completamente desintegrada.',['Feiticeiro','Mago']),
  s('Olhar Maligno',6,'Necromancia','1 ação','18 metros','Concentração, 1 min',true,false,false,'','Olhar para criatura: 1d4 semanas de efeito (cegueira, encantamento, assustado, náusea) até TR Sab em cada turno.',['Bardo','Feiticeiro','Mago','Bruxo']),
  s('Carne em Pedra',6,'Transmutação','1 ação','18 metros','Concentração, 1 min',true,false,true,'Ferromenganês','TR Constituição ou gradualmente petrificado (3 falhas = petrificado permanente).',['Feiticeiro','Mago','Bruxo']),
  s('Globo de Invulnerabilidade',6,'Abjuração','1 ação','Pessoal','Concentração, 1 min',true,false,true,'Pérola de vidro','Esfera de 3m de raio: magias de nível 5 ou menor não podem penetrá-la.',['Feiticeiro','Mago']),
  s('Causar Dano',6,'Necromancia','1 ação','Toque','Instantâneo',true,false,false,'','Toque: 14d6 necrótico. TR Constituição: 7d6.',['Clérico']),
  s('Curar',6,'Evocação','1 ação','18 metros','Instantâneo',true,false,false,'','Criatura recupera 70 PV. Remove doenças, cegueira e surdez.',['Clérico','Druida']),
  s('Banquete dos Heróis',6,'Conjuração','10 minutos','Pessoal','Instantâneo',true,false,true,'Uma tigela dourada de 1.000 po','Festim mágico: cura de doenças, imunidade a veneno e medo, 2d10 PV máximos e vantagem em TRs Sab por 24h.',['Clérico','Druida']),
  s('Frasco Mágico',6,'Necromancia','1 minuto','Toque','Até ser dissipada',true,false,true,'Gema de 500 po','Projeta sua consciência para possuir criatura cujo corpo está no frasco. Ou pode possuir corpo de criatura.',['Mago']),
  s('Sugestão em Massa',6,'Encantamento','1 ação','18 metros','24 horas',true,false,true,'Língua de cobra e mel','Como Sugestão, mas afeta até 12 criaturas.',['Bardo','Feiticeiro','Mago','Bruxo']),
  s('Esfera Congelante',6,'Evocação','1 ação','27 metros','Instantâneo',true,false,true,'Bola de cristal de 1.500 po','Esfera de gelo de 3m de raio: 10d6 frio (TR Constituição metade). Pode congelar superfície de água.',['Mago']),
  s('Dança Irresistível',6,'Encantamento','1 ação','9 metros','Concentração, 1 min',true,false,false,'','Criatura TR Sab ou começa a dançar: -4 CA, desvantagem em TR Dex, nenhuma ação além de dançar.',['Bardo','Mago']),
  s('Raio Solar',6,'Evocação','1 ação','Pessoal (linha de 54m)','Concentração, 1 min',true,false,false,'','Raio de luz solar: 6d8 radiante (TR Constituição metade) e cego até o fim do próximo turno. Como ação, dispara novo raio.',['Clérico','Druida','Feiticeiro','Mago']),
  s('Transporte por Plantas',6,'Conjuração','1 ação','3 metros','1 turno',true,false,false,'','Entre em planta de tamanho Grande+ e saia de qualquer planta similar no mesmo plano.',['Druida']),
  s('Visão Verdadeira',6,'Adivinhação','1 ação','Toque','1 hora',true,false,true,'Pomada de 25 po para os olhos','Concede visão verdadeira: ilusões, formas originais, Plano Etéreo, em escuridão mágica até 36m.',['Bardo','Clérico','Mago','Bruxo']),
  s('Muro de Gelo',6,'Evocação','1 ação','36 metros','Concentração, 10 min',true,false,true,'Pó de quartzo','Muro de gelo de até 10 painéis de 3m x 3m. 6d6 frio ao atravessar; fragmentos: 2d6 frio (TR Dex).',['Mago']),
  s('Muro de Espinhos',6,'Conjuração','1 ação','45 metros','Concentração, 10 min',true,false,true,'Um punhado de espinhos','Cilindro de espinhos: 7d8 perfurante ao entrar/começar turno (TR Dex metade).',['Druida']),
  s('Andar no Vento',6,'Transmutação','1 ação','9 metros','8 horas',true,false,false,'','Até 10 criaturas transformam-se em nuvens gasosas com velocidade de voo de 27m.',['Druida']),
  s('Palavra de Retorno',6,'Conjuração','1 ação','5 metros','Instantâneo',true,false,false,'','Você e até 5 aliados voluntários são teleportados ao seu santuário.',['Clérico']),
];

// ─── Nível 7 ──────────────────────────────────────────────────────────────────
const LEVEL_7:DndSpellData[]=[
  s('Convocar Celestial',7,'Conjuração','1 minuto','18 metros','Concentração, 1h',true,false,true,'Offerta de 25 po','Convoca celestial de CR 4 ou menor que obedece seus comandos.',['Clérico']),
  s('Bola de Fogo Retardada',7,'Evocação','1 ação','27 metros','Concentração, 1 min',true,false,true,'Guano de morcego e enxofre','Lança bola flamejante que pode ser detonada quando desejar. 12d6 fogo em esfera de 6m (TR Dex metade).',['Feiticeiro','Mago']),
  s('Palavra Divina',7,'Evocação','1 ação bônus','9 metros','Instantâneo',true,false,false,'','Criaturas com PV até 20: mortas; 30: cegas; 40: surdas; 50: atordoadas. Também bane celestiais/demônios/fadas que falhem.',['Clérico']),
  s('Incorporeidade',7,'Transmutação','1 ação','Pessoal','8 horas',true,false,false,'','Você pode mover-se pelo Plano Etéreo a qualquer momento. Resistência a dano não-mágico.',['Bardo','Clérico','Feiticeiro','Mago','Bruxo']),
  s('Dedo da Morte',7,'Necromancia','1 ação','18 metros','Instantâneo',true,false,false,'','TR Constituição ou 7d8+30 necrótico (metade em sucesso). Criatura humanóide morta por isso levanta como zumbi.',['Feiticeiro','Mago','Bruxo']),
  s('Tempestade de Fogo',7,'Evocação','1 ação','45 metros','Instantâneo',true,false,false,'','Até 10 cubos de 3m de fogo: 7d10 fogo (TR Dex metade). Vegetação não dispersa.',['Clérico','Druida','Feiticeiro']),
  s('Gaiola de Força',7,'Evocação','1 ação','27 metros','1 hora',false,true,false,'','Prisão de força invulnerável: cubo de até 6m. Nada entra ou sai (exceto ar).',['Bardo','Mago','Bruxo']),
  s('Miragem Arcana',7,'Ilusão','10 minutos','Pessoal','10 dias',true,true,false,'','Terreno em 1,5 km transforma aparência (luz, terreno, vegetação, cheiro, temperatura).',['Bardo','Druida','Mago']),
  s('Mansão Magnífica',7,'Conjuração','1 minuto','3 metros','24 horas',true,true,true,'Porta em miniatura de madolefim de 50 po','Porta extradimensional para mansão com 50 quartos e serventes fantasmas.',['Bardo','Mago']),
  s('Desvio Planar',7,'Conjuração','1 ação','3 metros','Instantâneo',true,false,true,'Diapasão de 250 po ajustado ao plano','Você e até 8 aliados viajam para outro plano. Ou bane criatura para seu plano (TR Carisma).',['Clérico','Druida','Feiticeiro','Mago','Bruxo']),
  s('Aspersão Prismática',7,'Evocação','1 ação','Pessoal (cone de 18m)','Instantâneo',true,false,false,'','8 raios coloridos aleatórios: cego, fogo, frio, elétrico, ácido, veneno, petrificado, ou teletransportado para outro plano.',['Feiticeiro','Mago']),
  s('Símbolo',7,'Abjuração','1 minuto','Toque','Até ser acionado',true,false,true,'Mercúrio, fósforo, diamante de 1.000 po','Glifo que ao ser acionado afeta criaturas numa esfera de 18m de raio (morte, discórdia, medo, etc.).',['Bardo','Clérico','Mago']),
  s('Regenerar',7,'Transmutação','1 minuto','Toque','1 hora',true,false,true,'Semente de figueira e mel','Recupera 4d8+15 PV imediatamente e 1 PV/turno por 1 hora. Membros decepados regeneram em 2 min.',['Bardo','Clérico','Druida']),
  s('Inverter Gravidade',7,'Transmutação','1 ação','27 metros','Concentração, 1 min',true,false,false,'','Gravidade invertida num cilindro de 18m de raio e 27m de altura. Criaturas caem para cima.',['Druida','Feiticeiro','Mago']),
  s('Ressurreição',7,'Necromancia','1 hora','Toque','Instantâneo',true,false,true,'Diamante de 1.000 po, consumido','Traz de volta criatura morta há até 100 anos com todos os PV.',['Bardo','Clérico']),
  s('Teletransporte',7,'Conjuração','1 ação','3 metros','Instantâneo',true,false,false,'','Você e até 8 criaturas são teleportados instantaneamente para destino familiar (chance de falha se desconhecido).',['Bardo','Feiticeiro','Mago']),
];

// ─── Nível 8 ──────────────────────────────────────────────────────────────────
const LEVEL_8:DndSpellData[]=[
  s('Murcha Horrível',8,'Necromancia','1 ação','45 metros','Instantâneo',true,false,true,'Esponja','TR Constituição ou 12d8 necrótico (metade em sucesso). Dobro de dano para vegetais/plantas.',['Feiticeiro','Mago']),
  s('Campo Antimagia',8,'Abjuração','1 ação','Pessoal','Concentração, 1h',true,false,false,'','Esfera de 3m de raio suprime magia: spells não funcionam, itens mágicos ficam inertes.',['Clérico','Mago']),
  s('Antipatia/Simpatia',8,'Encantamento','1 hora','18 metros','10 dias',true,false,true,'Vinagre/mel','Faz objeto/área ser atraente ou repulsiva para tipo específico de criatura.',['Druida','Mago']),
  s('Clone',8,'Necromancia','1 hora','Toque','Instantâneo',true,false,true,'Diamante de 1.000 po','Cria clone inconsciente de criatura. Se o original morrer, a alma vai para o clone.',['Mago']),
  s('Controlar o Clima',8,'Transmutação','10 minutos','Pessoal','Concentração, 8h',true,true,false,'','Controla clima num raio de 8 km: precipitação, temperatura e vento.',['Clérico','Druida','Mago']),
  s('Demiplano',8,'Conjuração','1 ação','18 metros','1 hora',false,true,false,'','Porta para demiplano extradimensional de 9m cúbicos. Permanece por 1 hora.',['Mago','Bruxo']),
  s('Dominar Monstro',8,'Encantamento','1 ação','18 metros','Concentração, 1h',true,false,false,'','Qualquer criatura TR Sab ou fica sob controle telepático. TR repetido a cada hora.',['Bardo','Feiticeiro','Mago','Bruxo']),
  s('Terremoto',8,'Evocação','1 ação','150 metros','Concentração, 1 min',true,false,false,'','Tremor em 30m de raio: terreno difícil, estruturas sofrem dano, TR Constituição ou prostrado.',['Clérico','Druida','Feiticeiro']),
  s('Confundir Mente',8,'Encantamento','1 ação','18 metros','Instantâneo',true,false,true,'Um polvo','TR Inteligência ou Int/Cari reduzidos a 1 e incapaz de conjurar. TR repetido a cada 30 dias.',['Bardo','Druida','Feiticeiro','Mago','Bruxo']),
  s('Aura Sagrada',8,'Abjuração','1 ação','Pessoal','Concentração, 1 min',true,false,true,'Uma relíquia sagrada de 1.000 po','Aura de 9m: aliados têm vantagem em TRs, atacantes têm desvantagem. Mortos-vivos ficam cegos ao atacar.',['Clérico']),
  s('Labirinto',8,'Conjuração','1 ação','18 metros','Concentração, 10 min',true,false,false,'','Banish criatura para labirinto extradimensional. TR Int (DC 20) como ação para escapar.',['Mago']),
  s('Mente em Branco',8,'Abjuração','1 ação','Toque','24 horas',true,false,false,'','Criatura imune a adivinhação e magia psíquica, e não pode ser lida ou influenciada.',['Bardo','Mago']),
  s('Palavra de Poder: Atordoar',8,'Encantamento','1 ação','18 metros','Instantâneo',true,false,false,'','Criatura com 150 PV ou menos fica atordoada. TR Constituição no fim de cada turno para recuperar.',['Bardo','Feiticeiro','Mago','Bruxo']),
  s('Palavra da Morte Iminente',8,'Necromancia','1 ação','18 metros','Instantâneo',true,false,false,'','Criatura com 100 PV ou menos morre. Caso contrário, sofre 12d12 necrótico.',['Mago','Bruxo']),
  s('Explosão Solar',8,'Evocação','1 ação','45 metros','Instantâneo',true,false,false,'','Esfera de 18m de raio de luz solar: 12d6 radiante (TR Constituição metade) e cega por 1 min.',['Druida','Feiticeiro','Mago']),
  s('Tsunami',8,'Conjuração','1 minuto','Visão','Concentração, 6 turnos',true,false,false,'','Muro de água de 30m de comprimento e altura. 6d10 contundente e derruba criaturas.',['Druida']),
];

// ─── Nível 9 ──────────────────────────────────────────────────────────────────
const LEVEL_9:DndSpellData[]=[
  s('Projeção Astral',9,'Necromancia','1 hora','3 metros','Especial',true,false,true,'Hiácinto de 1.000 po e colar de prata de 100 po','Você e até 8 aliados projetam corpos astrais para o Plano Astral.',['Clérico','Druida','Mago','Bruxo']),
  s('Presciência',9,'Adivinhação','1 minuto','Toque','8 horas',true,false,true,'Pluma de um pássaro raro','Criatura toca ganha vantagem em todos os ataques, testes e TRs pelas próximas 8 horas.',['Bardo','Druida','Mago','Bruxo']),
  s('Portão',9,'Conjuração','1 ação','18 metros','Concentração, 1 min',true,false,true,'Diamante de 5.000 po','Cria portal entre planos de existência. Pode também chamar criatura específica pelo nome.',['Clérico','Feiticeiro','Mago','Bruxo']),
  s('Aprisionamento',9,'Abjuração','1 minuto','9 metros','Até ser dissipada',true,false,true,'Componentes de 500 po','TR Sab ou criatura aprisionada (gaiola, dormindo, petrificada, encadeada, enterrada, etc.).',['Mago','Bruxo']),
  s('Cura em Massa',9,'Evocação','1 ação','18 metros','Instantâneo',true,false,false,'','Cura até 700 PV divididos entre qualquer número de criaturas visíveis.',['Clérico']),
  s('Enxame de Meteoros',9,'Evocação','1 ação','1,5 km','Instantâneo',true,false,false,'','Quatro bolas de fogo: 20d6 fogo + 20d6 contundente cada em esferas de 12m (TR Dex metade).',['Feiticeiro','Mago']),
  s('Palavra de Poder: Curar',9,'Evocação','1 ação','Toque','Instantâneo',true,false,false,'','Criatura recupera todos os PV e remove condições: charmed, frightened, paralised, stunned.',['Bardo','Clérico']),
  s('Palavra de Poder: Matar',9,'Encantamento','1 ação','18 metros','Instantâneo',true,false,false,'','Criatura com 100 PV ou menos morre instantaneamente.',['Bardo','Feiticeiro','Mago','Bruxo']),
  s('Muro Prismático',9,'Abjuração','1 ação','18 metros','10 minutos',true,false,false,'','Muro de 18m x 9m com 7 camadas coloridas. Cada camada causa efeito diferente aos que atravessam.',['Mago']),
  s('Grito Psíquico',9,'Encantamento','1 ação','Sem limite','Instantâneo',false,true,false,'','Até 10 criaturas que você veja: TR Inteligência ou 14d6 psíquico e atordoado por 1 min.',['Bardo','Feiticeiro','Mago','Bruxo']),
  s('Mudar de Forma',9,'Transmutação','1 ação','Pessoal','Concentração, 1h',true,false,true,'Serpentina','Transforma-se em qualquer criatura com CR igual ou menor ao seu nível. PV e habilidades da nova forma.',['Druida','Mago']),
  s('Tempestade de Vingança',9,'Conjuração','1 ação','Visão','Concentração, 1 min',true,false,false,'','Nuvem cobrindo 6 km de raio. Dez relâmpagos por turno (10d6 elétrico), granizo, ventos violentos e chuva ácida.',['Druida']),
  s('Feitiço de Tempo',9,'Transmutação','1 ação','Pessoal','Concentração, 1 min',true,false,false,'','Você recebe dois turnos extras agora e no início de cada turno enquanto concentrado.',['Feiticeiro','Mago']),
  s('Polimorfo Verdadeiro',9,'Transmutação','1 ação','9 metros','Concentração, 1h',true,false,true,'Um casulo','Transforma criatura em qualquer criatura ou objeto. Se mantido por 1h de concentração, torna-se permanente.',['Bardo','Bruxo']),
  s('Ressurreição Verdadeira',9,'Necromancia','1 hora','Toque','Instantâneo',true,false,true,'Diamante de 25.000 po','Traz de volta criatura morta há até 200 anos com corpo completamente restaurado.',['Clérico','Druida']),
  s('Estranheza',9,'Ilusão','1 ação','36 metros','Concentração, 1 min',true,false,false,'','Criaturas numa esfera de 9m TR Sab ou ficam amedrontadas. Enquanto amedrontadas: 4d10 psíquico/turno.',['Mago']),
  s('Desejo',9,'Conjuração','1 ação','Pessoal','Instantâneo',true,false,false,'','A magia mais poderosa. Replique qualquer magia de nível 8 ou inferior, ou realize um desejo. Uso além de replicar: 33% de nunca mais poder lançar Desejo.',['Feiticeiro','Mago']),
  s('Arrependimento',9,'Abjuração','1 hora','Toque','Instantâneo',true,false,true,'Item sagrado de 1.000 po','Remove qualquer efeito mágico, restaura memória, cura transformação permanente.',['Clérico']),
];

// ─── Export ───────────────────────────────────────────────────────────────────
export const ALL_DND_SPELLS:DndSpellData[]=[
  ...CANTRIPS,...LEVEL_1,...LEVEL_2,...LEVEL_3,...LEVEL_4,...LEVEL_5,...LEVEL_6,...LEVEL_7,...LEVEL_8,...LEVEL_9,
];
